### ISSUE TITLE
RTX 3070 with CUDA capability sm_86 is not compatible with the current Pytorch installation.

### ISSUE THREAD

**Issue by BIT-wangzb** [StephLin/SE-SSD-ROS#8]
I have compiled `SE-SSD-ROS` successfully. But when ran `python3 ros_main.py`，I got an error: `RTX 3070 with CUDA capability sm_86 is not compatible with the current Pytorch installation`. I tried to solve this problem, but failed. How can I fix it?

**Comment by StephLin** [comment]
Hi @BIT-wangzb,

Sorry for the late reply. I'm not sure if this issue is resolved by yourself, but you may need to check if your Pytorch version is compatible with your CUDA version. Probably you need to compile Pytorch from source instead of downloading prebuilt Pytorch wheels to support CUDA 11.x (the version that RTX 3070 supports I thought).

I close this issue for now. Feel free to re-open it if needed.
